import type { Language } from "./apiClient";

export const PORTAL_COPY: Record<Language, {
  welcome: string; manage: string; open: string; none: string;
  parentPortal: string; parentIntro: string; upcoming: string; resources: string; recent: string; viewAll: string;
  professionalPortal: string; waiting: string; resolved: string; completed: string; next: string; approval: string;
  governmentPortal: string; aggregateTitle: string; aggregateIntro: string; governmentRequired: string;
  totalConversations: string; referred: string; consultationsResolved: string; appointmentsCompleted: string;
  topicEngagement: string; noTopic: string; languageSplit: string; facilitiesDistrict: string; noFacilities: string;
}> = {
  EN: { welcome: "Welcome", manage: "Manage", open: "Open", none: "Nothing scheduled yet.", parentPortal: "Parent & Guardian Portal", parentIntro: "Resources, appointments, and updates in one place.", upcoming: "Upcoming appointments", resources: "Educational resources", recent: "Recent notifications", viewAll: "View all", professionalPortal: "Healthcare Professional Portal", waiting: "Waiting on you", resolved: "Resolved consultations", completed: "Completed appointments", next: "Next up", approval: "Your professional account is awaiting administrator approval.", governmentPortal: "Government Portal", aggregateTitle: "Aggregated platform statistics", aggregateIntro: "Aggregated planning information only. Individual consultation and user records are not exposed here.", governmentRequired: "A government account is required.", totalConversations: "Total conversations", referred: "Referred to a professional", consultationsResolved: "Consultations resolved", appointmentsCompleted: "Appointments completed", topicEngagement: "Topic engagement", noTopic: "No topic activity yet.", languageSplit: "Language split", facilitiesDistrict: "Health facilities by district", noFacilities: "No facilities recorded yet." },
  RW: { welcome: "Murakaza neza", manage: "Cunga", open: "Fungura", none: "Nta gahunda iriho ubu.", parentPortal: "Urubuga rw'Ababyeyi n'Abarezi", parentIntro: "Amakuru, gahunda n'amatangazo hamwe.", upcoming: "Gahunda ziri imbere", resources: "Amakuru y'ubuzima", recent: "Amatangazo mashya", viewAll: "Reba byose", professionalPortal: "Urubuga rw'Abakozi b'Ubuzima", waiting: "Ibigutegereje", resolved: "Ibiganiro byakemuwe", completed: "Gahunda zarangiye", next: "Ibikurikira", approval: "Konti yawe y'umukozi w'ubuzima iracyategereje kwemezwa.", governmentPortal: "Urubuga rwa Leta", aggregateTitle: "Imibare rusange y'urubuga", aggregateIntro: "Amakuru rusange yo gufasha igenamigambi gusa. Amakuru bwite n'ibiganiro ntibigaragazwa.", governmentRequired: "Konti ya Leta irakenewe.", totalConversations: "Ibiganiro byose", referred: "Boherejwe ku mukozi w'ubuzima", consultationsResolved: "Ibiganiro byakemuwe", appointmentsCompleted: "Gahunda zarangiye", topicEngagement: "Ingingo zikunzwe", noTopic: "Nta makuru y'ingingo arahari.", languageSplit: "Imikoreshereze y'indimi", facilitiesDistrict: "Ibigo nderabuzima ku turere", noFacilities: "Nta bigo nderabuzima birandikwa." },
  FR: { welcome: "Bienvenue", manage: "Gérer", open: "Ouvrir", none: "Rien de prévu pour le moment.", parentPortal: "Portail Parents et Tuteurs", parentIntro: "Ressources, rendez-vous et mises à jour au même endroit.", upcoming: "Rendez-vous à venir", resources: "Ressources éducatives", recent: "Notifications récentes", viewAll: "Tout voir", professionalPortal: "Portail des Professionnels de Santé", waiting: "En attente de votre action", resolved: "Consultations résolues", completed: "Rendez-vous terminés", next: "À venir", approval: "Votre compte professionnel attend l'approbation d'un administrateur.", governmentPortal: "Portail Gouvernemental", aggregateTitle: "Statistiques agrégées de la plateforme", aggregateIntro: "Informations agrégées pour la planification uniquement. Aucun dossier individuel n'est affiché.", governmentRequired: "Un compte gouvernemental est requis.", totalConversations: "Total des conversations", referred: "Orientés vers un professionnel", consultationsResolved: "Consultations résolues", appointmentsCompleted: "Rendez-vous terminés", topicEngagement: "Intérêt par sujet", noTopic: "Aucune activité par sujet.", languageSplit: "Répartition linguistique", facilitiesDistrict: "Établissements par district", noFacilities: "Aucun établissement enregistré." },
  SW: { welcome: "Karibu", manage: "Dhibiti", open: "Fungua", none: "Hakuna kilichopangwa bado.", parentPortal: "Tovuti ya Wazazi na Walezi", parentIntro: "Rasilimali, miadi na taarifa mahali pamoja.", upcoming: "Miadi ijayo", resources: "Rasilimali za elimu", recent: "Arifa za hivi karibuni", viewAll: "Tazama zote", professionalPortal: "Tovuti ya Wataalamu wa Afya", waiting: "Vinavyokusubiri", resolved: "Mashauriano yaliyokamilika", completed: "Miadi iliyokamilika", next: "Inayofuata", approval: "Akaunti yako ya kitaalamu inasubiri idhini ya msimamizi.", governmentPortal: "Tovuti ya Serikali", aggregateTitle: "Takwimu za jumla za mfumo", aggregateIntro: "Taarifa za jumla kwa mipango pekee. Rekodi binafsi hazionyeshwi.", governmentRequired: "Akaunti ya serikali inahitajika.", totalConversations: "Mazungumzo yote", referred: "Waliopelekwa kwa mtaalamu", consultationsResolved: "Mashauriano yaliyokamilika", appointmentsCompleted: "Miadi iliyokamilika", topicEngagement: "Matumizi kwa mada", noTopic: "Hakuna shughuli za mada bado.", languageSplit: "Mgawanyo wa lugha", facilitiesDistrict: "Vituo vya afya kwa wilaya", noFacilities: "Hakuna vituo vilivyosajiliwa." },
};

export const HEALTH_TOPIC_NAMES: Record<Language, string[]> = {
  EN: ["Menstrual Health", "Pregnancy", "Relationships", "Family Planning", "HIV & STIs", "Mental Health"],
  RW: ["Ubuzima bw'imihango", "Gutwita", "Imibanire", "Kuboneza urubyaro", "VIH n'indwara zandurira mu mibonano", "Ubuzima bwo mu mutwe"],
  FR: ["Santé menstruelle", "Grossesse", "Relations", "Planification familiale", "VIH et IST", "Santé mentale"],
  SW: ["Afya ya hedhi", "Ujauzito", "Mahusiano", "Uzazi wa mpango", "VVU na magonjwa ya zinaa", "Afya ya akili"],
};
